version: "3"
services:
  listings-service:
    build: "./listings-service"
    depends_on:
      - listings-service-db
    environment:
      - DB_URI=${LISTINGS_DB_URI}
    ports:
      - ${LISTINGS_SERVICE_PORT}
    volumes:
      - ./listings-service:/opt/app

  listings-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${DB}
    image: ${IMAGE}
    ports:
      - ${LISTINGS_DB_PORT}

  users-service:
    build: "./users-service"
    depends_on:
      - users-service-db
    environment:
      - DB_URI=${USERS_DB_URI}
    ports:
      - ${USERS_SERVICE_PORT}
    volumes:
      - ./users-service:/opt/app

  users-service-db:
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=${DB}
    image: ${IMAGE}
    ports:
      - ${USERS_DB_PORT}
